// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-touch/9b10d0473fb5161c379df57d63d3d59fb5b62fb0/touch.d.ts
declare module '~touch/touch' {
function touch (filename: string, cb: (err: Error) => any): void;
function touch (filename: string, options: touch.Options, cb: (err: Error) => any): void;

namespace touch {

  export function sync (filename: string, options?: touch.Options): void;

  export function ftouch (filename: string, cb: (err: Error) => any): void;
  export function ftouch (filename: string, options: touch.Options, cb: (err: Error) => any): void;

  export function ftouchSync (filename: string, options?: touch.Options): void;

  export interface Options {
    force?: boolean;
    time?: Date | string | number;
    atime?: boolean | Date;
    mtime?: boolean | Date;
    ref?: string;
    nocreate?: boolean;
  }

}

export = touch;
}
declare module 'touch/touch' {
import main = require('~touch/touch');
export = main;
}
declare module 'touch' {
import main = require('~touch/touch');
export = main;
}
